import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Pencil, Plus, Save, ToggleLeft, ToggleRight, Trash2 } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

const DISTRICTS = ["中西區", "灣仔區", "東區", "南區", "油尖旺區", "深水埗區", "九龍城區", "黃大仙區", "觀塘區", "葵青區", "荃灣區", "屯門區", "元朗區", "北區", "大埔區", "沙田區", "西貢區", "離島區"] as const;
const SUBJECTS = ["中文", "英文", "數學", "Science"];
const GRADES = ["小一", "小二", "小三", "小四", "小五", "小六", "中一", "中二", "中三"];
const COMMISSION_LABELS = { pending: "待商議", fixed: "固定金額", percentage: "百分比", mixed: "混合方式" } as const;
type CommissionArrangement = keyof typeof COMMISSION_LABELS;
type CentreForm = { name: string; description: string; whatsapp: string; website: string; address: string; district: "" | typeof DISTRICTS[number]; subjects: string[]; supportedGrades: string[]; isActive: boolean; isFeatured: boolean; isPubliclyListed: boolean; commissionArrangement: CommissionArrangement; privatePartnerNote: string };
const blank: CentreForm = { name: "", description: "", whatsapp: "", website: "", address: "", district: "", subjects: [], supportedGrades: [], isActive: true, isFeatured: false, isPubliclyListed: false, commissionArrangement: "pending", privatePartnerNote: "" };
const parseList = (value: string) => { try { return JSON.parse(value) as string[]; } catch { return []; } };

export default function CentresAdmin() {
  const { user, loading } = useAuth();
  const [form, setForm] = useState<CentreForm>(blank);
  const [editingId, setEditingId] = useState<number | null>(null);
  const utils = trpc.useUtils();
  const isAdmin = user?.role === "admin";
  const centres = trpc.centres.adminList.useQuery(undefined, { enabled: isAdmin });
  const refreshCentres = () => { utils.centres.adminList.invalidate(); utils.centres.featured.invalidate(); };
  const create = trpc.centres.create.useMutation({ onSuccess: () => { refreshCentres(); setForm(blank); } });
  const update = trpc.centres.update.useMutation({ onSuccess: () => { refreshCentres(); setForm(blank); setEditingId(null); } });
  const setActive = trpc.centres.setActive.useMutation({ onSuccess: refreshCentres });
  const remove = trpc.centres.remove.useMutation({ onSuccess: refreshCentres });
  const error = create.error?.message || update.error?.message || setActive.error?.message || remove.error?.message;
  const title = useMemo(() => editingId ? "修改合作補習社" : "新增合作補習社", [editingId]);
  const toggle = (key: "subjects" | "supportedGrades", value: string) => setForm((current) => ({ ...current, [key]: current[key].includes(value) ? current[key].filter((item) => item !== value) : [...current[key], value] }));
  const submit = (event: FormEvent) => { event.preventDefault(); if (editingId) update.mutate({ id: editingId, centre: form as never }); else create.mutate(form as never); };
  const edit = (centre: NonNullable<typeof centres.data>[number]) => { setEditingId(centre.id); setForm({ name: centre.name, description: centre.description, whatsapp: centre.whatsapp, website: centre.website ?? "", address: centre.address ?? "", district: centre.district as CentreForm["district"], subjects: parseList(centre.subjects), supportedGrades: parseList(centre.supportedGrades), isActive: centre.isActive, isFeatured: centre.isFeatured, isPubliclyListed: centre.isPubliclyListed, commissionArrangement: centre.commissionArrangement, privatePartnerNote: centre.privatePartnerNote ?? "" }); window.scrollTo({ top: 0, behavior: "smooth" }); };

  return <DashboardLayout><div className="max-w-6xl mx-auto space-y-8 p-2 text-slate-900 md:p-8">
    <header className="border-b border-slate-200 pb-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Learning Compass · Admin</p><h1 className="mt-2 text-3xl font-serif text-emerald-950 md:text-4xl">十八區補習社資料管理</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">本頁把內部合作資料與公開展示分開管理。中心的私有 WhatsApp、合作安排及內部備註只供管理員查看；公開頁一律由學習航圖安排轉介。</p></header>
    {loading ? <p className="text-sm text-slate-500">正在檢查管理權限…</p> : !isAdmin ? <section className="rounded-xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-amber-900">需要管理員權限</h2><p className="mt-2 text-sm text-amber-800">請以已設定為管理員的帳戶登入後再管理補習社資料。</p></section> : <>
      <section className="rounded-2xl border border-emerald-200 bg-white p-5 shadow-sm md:p-7"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-xl font-bold text-emerald-950">{title}</h2>{editingId && <button className="text-sm text-emerald-800 underline" onClick={() => { setEditingId(null); setForm(blank); }}>取消修改</button>}</div>
        <form onSubmit={submit} className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium">補習社名稱<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="rounded-lg border border-slate-300 p-2.5" placeholder="請填寫真實名稱" /></label><label className="grid gap-1 text-sm font-medium">私有合作 WhatsApp<input required value={form.whatsapp} onChange={(event) => setForm({ ...form, whatsapp: event.target.value })} className="rounded-lg border border-slate-300 p-2.5" placeholder="只供內部聯絡，例如：9123 4567" /></label><label className="grid gap-1 text-sm font-medium">所在十八區<select required value={form.district} onChange={(event) => setForm({ ...form, district: event.target.value as CentreForm["district"] })} className="rounded-lg border border-slate-300 p-2.5"><option value="">請選擇</option>{DISTRICTS.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">地址（只在核准公開時使用）<input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} className="rounded-lg border border-slate-300 p-2.5" placeholder="例如：荃灣南豐中心 1609B 室" /></label><label className="grid gap-1 text-sm font-medium">網站（內部參考）<input value={form.website} onChange={(event) => setForm({ ...form, website: event.target.value })} className="rounded-lg border border-slate-300 p-2.5" placeholder="https://" /></label><label className="grid gap-1 text-sm font-medium">佣金安排<select value={form.commissionArrangement} onChange={(event) => setForm({ ...form, commissionArrangement: event.target.value as CommissionArrangement })} className="rounded-lg border border-slate-300 bg-white p-2.5">{Object.entries(COMMISSION_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
          <label className="grid gap-1 text-sm font-medium">真實服務介紹<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="min-h-24 rounded-lg border border-slate-300 p-2.5" placeholder="請填寫至少 10 字的真實服務介紹" /></label>
          <label className="grid gap-1 text-sm font-medium">私有合作備註<textarea value={form.privatePartnerNote} onChange={(event) => setForm({ ...form, privatePartnerNote: event.target.value })} className="min-h-20 rounded-lg border border-slate-300 p-2.5" placeholder="例如：條款待商議、中心負責人或內部跟進資訊；不會公開" /></label>
          <fieldset><legend className="mb-2 text-sm font-medium">支援科目</legend><div className="flex flex-wrap gap-2">{SUBJECTS.map((item) => <label key={item} className="inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm"><input type="checkbox" checked={form.subjects.includes(item)} onChange={() => toggle("subjects", item)} />{item}</label>)}</div></fieldset>
          <fieldset><legend className="mb-2 text-sm font-medium">適合年級</legend><div className="flex flex-wrap gap-2">{GRADES.map((item) => <label key={item} className="inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm"><input type="checkbox" checked={form.supportedGrades.includes(item)} onChange={() => toggle("supportedGrades", item)} />{item}</label>)}</div></fieldset>
          <div className="flex flex-wrap gap-5 text-sm"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} />已啟用合作關係</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={form.isPubliclyListed} onChange={(event) => setForm({ ...form, isPubliclyListed: event.target.checked })} />核准公開基本資料</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={form.isFeatured} disabled={!form.isPubliclyListed} onChange={(event) => setForm({ ...form, isFeatured: event.target.checked })} />在首頁熱門推薦顯示</label></div>
          <p className="text-xs leading-5 text-slate-500">即使核准公開，中心 WhatsApp、合作條款與內部備註也不會出現在首頁；家長只可按「由學習航圖安排轉介」聯絡管理方。</p>
          {error && <p className="text-sm text-red-700">{error}</p>}<button disabled={create.isPending || update.isPending} className="inline-flex items-center gap-2 rounded-lg bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{editingId ? <Save size={16} /> : <Plus size={16} />}{create.isPending || update.isPending ? "儲存中…" : editingId ? "儲存修改" : "新增補習社"}</button></form>
      </section>
      <section><div className="mb-4"><h2 className="text-xl font-bold text-emerald-950">現有合作資料</h2><p className="mt-1 text-sm text-slate-600">{centres.data?.length ?? 0} 間已建立資料。公開推薦需要同時「已啟用」、「核准公開」及「熱門顯示」。</p></div>
        {centres.isLoading ? <p className="text-sm text-slate-500">正在讀取…</p> : centres.data?.length ? <div className="grid gap-3">{centres.data.map((centre) => <article key={centre.id} className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4 md:flex-row md:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-emerald-950">{centre.name}</h3>{centre.isPubliclyListed && <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-800">已核准公開</span>}{centre.isFeatured && <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-bold text-amber-800">首頁熱門</span>}{!centre.isActive && <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">未啟用</span>}</div><p className="mt-1 text-sm text-slate-600">{centre.district} · {centre.region} · {parseList(centre.subjects).join("、")} · 佣金：{COMMISSION_LABELS[centre.commissionArrangement]}</p></div><div className="flex flex-wrap gap-2"><button disabled={setActive.isPending} onClick={() => setActive.mutate({ id: centre.id, isActive: !centre.isActive })} className={centre.isActive ? "inline-flex items-center gap-1 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900 disabled:opacity-60" : "inline-flex items-center gap-1 rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-sm text-emerald-900 disabled:opacity-60"}>{centre.isActive ? <ToggleRight size={16} /> : <ToggleLeft size={16} />}{setActive.isPending ? "更新中…" : centre.isActive ? "停用" : "啟用"}</button><button onClick={() => edit(centre)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><Pencil size={15} />修改</button><button onClick={() => { if (window.confirm(`確定刪除「${centre.name}」？`)) remove.mutate({ id: centre.id }); }} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700"><Trash2 size={15} />刪除</button></div></article>)}</div> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-700" /><h3 className="mt-3 font-bold text-emerald-950">尚未加入合作補習社</h3><p className="mt-1 text-sm text-slate-600">請以真實合作資料建立第一筆記錄；公開展示由你在本頁明確核准後才會出現。</p></div>}
      </section>
    </>}</div></DashboardLayout>;
}
