#!/usr/bin/env python3
"""Review one grade-track question batch with a structured LLM moderation pass.

Usage: python3 scripts/review-question-batch.py P1 chinese-reading
Requires: audit/question-bank-inventory.json generated by pnpm audit:questions.
"""

import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


if len(sys.argv) != 3:
    raise SystemExit("Usage: review-question-batch.py <grade> <track>")

grade, track = sys.argv[1], sys.argv[2]
chunk_size = int(os.environ.get("REVIEW_CHUNK_SIZE", "0"))
if chunk_size < 0:
    raise SystemExit("REVIEW_CHUNK_SIZE must be 0 or a positive integer")
review_model = os.environ.get("REVIEW_MODEL", "gpt-5")
root = Path(__file__).resolve().parents[1]
inventory_path = root / "audit" / "question-bank-inventory.json"
inventory = json.loads(inventory_path.read_text())

# Variant 0 is the canonical source item. Variants 1 and 2 only append a context
# label, and the structural inventory separately confirms their options and answer
# indexes remain identical.
questions = [
    item
    for item in inventory["questions"]
    if item["grade"] == grade and item["id"].startswith(f"{track}-{grade}-") and item["id"].endswith("-0")
]
if not questions:
    raise SystemExit(f"No canonical questions found for {grade} {track}")

schema = {
    "name": "question_batch_review",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "batchSummary": {"type": "string"},
            "reviews": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "string"},
                        "verdict": {"type": "string", "enum": ["PASS", "REVISE", "ESCALATE"]},
                        "answerCorrect": {"type": "boolean"},
                        "singleBestAnswer": {"type": "boolean"},
                        "gradeAppropriate": {"type": "boolean"},
                        "difficultyJudgement": {"type": "string", "enum": ["too_easy", "appropriate", "too_hard", "out_of_scope"]},
                        "reason": {"type": "string"},
                        "recommendedQuestion": {"type": "string"},
                        "recommendedOptions": {"type": "array", "items": {"type": "string"}},
                        "recommendedCorrect": {"type": "integer"}
                    },
                    "required": ["id", "verdict", "answerCorrect", "singleBestAnswer", "gradeAppropriate", "difficultyJudgement", "reason", "recommendedQuestion", "recommendedOptions", "recommendedCorrect"],
                    "additionalProperties": False
                }
            }
        },
        "required": ["batchSummary", "reviews"],
        "additionalProperties": False
    }
}

system = """You are a meticulous Hong Kong primary and junior-secondary assessment moderator. You review every multiple-choice item independently. Determine the mathematical/language/science answer yourself; do not trust the supplied answer. For the stated grade, demand age-appropriate language and syllabus-adjacent knowledge. 'Deep' means richer reasoning inside the grade level, not cross-grade content. Reject ambiguous stems, weak distractors, more than one defensible answer, or a mismatch between the claimed ability and the item. Keep exact original content when it passes. When revision is needed, write a complete replacement item with exactly four options and a zero-based correct index. Return only the requested JSON."""

def review_chunk(items: list[dict], part: int, total_parts: int) -> dict:
    payload = {
        "model": review_model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": json.dumps({
                "task": "Review this portion of one grade-track batch. Every listed item has two context-only variants with the same answer/options; your verdict applies to all three variants unless the item itself needs revision.",
                "grade": grade,
                "track": track,
                "part": f"{part} of {total_parts}",
                "items": [{
                    "id": item["id"], "label": item["label"], "topic": item["topic"],
                    "question": item["question"], "hint": item["hint"], "options": item["options"],
                    "suppliedCorrectIndex": item["correct"], "suppliedAnswer": item["answer"],
                    "difficulty": item["difficulty"], "module": item["module"],
                } for item in items],
            }, ensure_ascii=False)},
        ],
        "response_format": {"type": "json_schema", "json_schema": schema},
        "max_completion_tokens": 6000 if chunk_size else 10000,
        "reasoning": {"effort": "high"},
    }
    request = urllib.request.Request(
        f"{os.environ['OPENAI_API_BASE'].rstrip('/')}/chat/completions",
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={"Authorization": f"Bearer {os.environ['OPENAI_API_KEY']}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=300) as response:
        result = json.loads(response.read())
    reviewed = json.loads(result["choices"][0]["message"]["content"])
    found_ids = {item["id"] for item in reviewed["reviews"]}
    expected_ids = {item["id"] for item in items}
    if found_ids != expected_ids:
        raise RuntimeError(f"Review did not cover exactly the requested IDs. Missing={expected_ids - found_ids}; extra={found_ids - expected_ids}")
    return reviewed


chunks = [questions] if not chunk_size else [questions[index:index + chunk_size] for index in range(0, len(questions), chunk_size)]
chunk_reviews = [review_chunk(chunk, index + 1, len(chunks)) for index, chunk in enumerate(chunks)]
review = {
    "batchSummary": "\n\n".join(f"Part {index + 1}/{len(chunk_reviews)}: {item['batchSummary']}" for index, item in enumerate(chunk_reviews)),
    "reviews": [entry for item in chunk_reviews for entry in item["reviews"]],
}

output = {
    "generatedAt": datetime.now(timezone.utc).isoformat(),
    "grade": grade,
    "track": track,
    "canonicalQuestionCount": len(questions),
    "variantQuestionCount": len(questions) * 3,
    "model": review_model,
    "review": review,
}
output_path = root / "audit" / f"review-{grade}-{track}.json"
output_path.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n")
print(f"Wrote {output_path.relative_to(root)}")
print(f"Reviewed {len(questions)} canonical items / {len(questions) * 3} context variants.")
